SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 720

ASTEROID_MIN_RADIUS: float = 20
ASTEROID_KINDS: int = 3
ASTEROID_SPAWN_RATE: float = 0.8  # seconds
ASTEROID_MAX_RADIUS: float = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_SCORE: int = 50

PLAYER_RADIUS: float = 20
PLAYER_TURN_SPEED: float = 300
PLAYER_SPEED: float = 200

PLAYER_SHOOT_SPEED: float = 500
PLAYER_SHOOT_COOLDOWN: float = 0.3
SHOT_RADIUS: float = 5

SCORE_TIME_INCREMENT: int = 5
LIFE_LOST_SCORE_PENALTY: int = 1000
MAX_LIVES: int = 3
INVINCIBILITY_TIME: int = 2500  # milliseconds

PARTICLE_RADIUS = 2
